web:
  resource-path: D:/浏览器下载/tstcms/dreamer-cms/

spring: 
  datasource: 
    name: prd
    url: jdbc:mysql://127.0.0.1:3389/dreamer-cms?serverTimezone=GMT&useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: root3306!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    password:
    jedis:
      pool:
        max-idle: 100
        min-idle: 50
        max-wait: -1